/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IConverter } from "../IConverter";

export class IConverter__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConverter {
    return new Contract(address, _abi, signerOrProvider) as IConverter;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "_token_amount",
        type: "uint256",
      },
      {
        internalType: "int128",
        name: "i",
        type: "int128",
      },
    ],
    name: "calc_withdraw_one_coin",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
