/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IUpgradeSource } from "../IUpgradeSource";

export class IUpgradeSource__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUpgradeSource {
    return new Contract(address, _abi, signerOrProvider) as IUpgradeSource;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "finalizeUpgrade",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "shouldUpgrade",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
