/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BaseUpgradeableStrategyStorageInterface
  extends ethers.utils.Interface {
  functions: {
    "nextImplementation()": FunctionFragment;
    "nextImplementationDelay()": FunctionFragment;
    "nextImplementationTimestamp()": FunctionFragment;
    "pausedInvesting()": FunctionFragment;
    "profitSharingDenominator()": FunctionFragment;
    "profitSharingNumerator()": FunctionFragment;
    "rewardPool()": FunctionFragment;
    "rewardToken()": FunctionFragment;
    "sell()": FunctionFragment;
    "sellFloor()": FunctionFragment;
    "underlying()": FunctionFragment;
    "vault()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "nextImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextImplementationDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextImplementationTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pausedInvesting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "profitSharingDenominator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "profitSharingNumerator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sell", values?: undefined): string;
  encodeFunctionData(functionFragment: "sellFloor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "underlying",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "nextImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextImplementationDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextImplementationTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pausedInvesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "profitSharingDenominator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "profitSharingNumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewardPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellFloor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "underlying", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;

  events: {};
}

export class BaseUpgradeableStrategyStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BaseUpgradeableStrategyStorageInterface;

  functions: {
    nextImplementation(overrides?: CallOverrides): Promise<[string]>;

    "nextImplementation()"(overrides?: CallOverrides): Promise<[string]>;

    nextImplementationDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    "nextImplementationDelay()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    nextImplementationTimestamp(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "nextImplementationTimestamp()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pausedInvesting(overrides?: CallOverrides): Promise<[boolean]>;

    "pausedInvesting()"(overrides?: CallOverrides): Promise<[boolean]>;

    profitSharingDenominator(overrides?: CallOverrides): Promise<[BigNumber]>;

    "profitSharingDenominator()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    profitSharingNumerator(overrides?: CallOverrides): Promise<[BigNumber]>;

    "profitSharingNumerator()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    rewardPool(overrides?: CallOverrides): Promise<[string]>;

    "rewardPool()"(overrides?: CallOverrides): Promise<[string]>;

    rewardToken(overrides?: CallOverrides): Promise<[string]>;

    "rewardToken()"(overrides?: CallOverrides): Promise<[string]>;

    sell(overrides?: CallOverrides): Promise<[boolean]>;

    "sell()"(overrides?: CallOverrides): Promise<[boolean]>;

    sellFloor(overrides?: CallOverrides): Promise<[BigNumber]>;

    "sellFloor()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    underlying(overrides?: CallOverrides): Promise<[string]>;

    "underlying()"(overrides?: CallOverrides): Promise<[string]>;

    vault(overrides?: CallOverrides): Promise<[string]>;

    "vault()"(overrides?: CallOverrides): Promise<[string]>;
  };

  nextImplementation(overrides?: CallOverrides): Promise<string>;

  "nextImplementation()"(overrides?: CallOverrides): Promise<string>;

  nextImplementationDelay(overrides?: CallOverrides): Promise<BigNumber>;

  "nextImplementationDelay()"(overrides?: CallOverrides): Promise<BigNumber>;

  nextImplementationTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  "nextImplementationTimestamp()"(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  pausedInvesting(overrides?: CallOverrides): Promise<boolean>;

  "pausedInvesting()"(overrides?: CallOverrides): Promise<boolean>;

  profitSharingDenominator(overrides?: CallOverrides): Promise<BigNumber>;

  "profitSharingDenominator()"(overrides?: CallOverrides): Promise<BigNumber>;

  profitSharingNumerator(overrides?: CallOverrides): Promise<BigNumber>;

  "profitSharingNumerator()"(overrides?: CallOverrides): Promise<BigNumber>;

  rewardPool(overrides?: CallOverrides): Promise<string>;

  "rewardPool()"(overrides?: CallOverrides): Promise<string>;

  rewardToken(overrides?: CallOverrides): Promise<string>;

  "rewardToken()"(overrides?: CallOverrides): Promise<string>;

  sell(overrides?: CallOverrides): Promise<boolean>;

  "sell()"(overrides?: CallOverrides): Promise<boolean>;

  sellFloor(overrides?: CallOverrides): Promise<BigNumber>;

  "sellFloor()"(overrides?: CallOverrides): Promise<BigNumber>;

  underlying(overrides?: CallOverrides): Promise<string>;

  "underlying()"(overrides?: CallOverrides): Promise<string>;

  vault(overrides?: CallOverrides): Promise<string>;

  "vault()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    nextImplementation(overrides?: CallOverrides): Promise<string>;

    "nextImplementation()"(overrides?: CallOverrides): Promise<string>;

    nextImplementationDelay(overrides?: CallOverrides): Promise<BigNumber>;

    "nextImplementationDelay()"(overrides?: CallOverrides): Promise<BigNumber>;

    nextImplementationTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    "nextImplementationTimestamp()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pausedInvesting(overrides?: CallOverrides): Promise<boolean>;

    "pausedInvesting()"(overrides?: CallOverrides): Promise<boolean>;

    profitSharingDenominator(overrides?: CallOverrides): Promise<BigNumber>;

    "profitSharingDenominator()"(overrides?: CallOverrides): Promise<BigNumber>;

    profitSharingNumerator(overrides?: CallOverrides): Promise<BigNumber>;

    "profitSharingNumerator()"(overrides?: CallOverrides): Promise<BigNumber>;

    rewardPool(overrides?: CallOverrides): Promise<string>;

    "rewardPool()"(overrides?: CallOverrides): Promise<string>;

    rewardToken(overrides?: CallOverrides): Promise<string>;

    "rewardToken()"(overrides?: CallOverrides): Promise<string>;

    sell(overrides?: CallOverrides): Promise<boolean>;

    "sell()"(overrides?: CallOverrides): Promise<boolean>;

    sellFloor(overrides?: CallOverrides): Promise<BigNumber>;

    "sellFloor()"(overrides?: CallOverrides): Promise<BigNumber>;

    underlying(overrides?: CallOverrides): Promise<string>;

    "underlying()"(overrides?: CallOverrides): Promise<string>;

    vault(overrides?: CallOverrides): Promise<string>;

    "vault()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    nextImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    "nextImplementation()"(overrides?: CallOverrides): Promise<BigNumber>;

    nextImplementationDelay(overrides?: CallOverrides): Promise<BigNumber>;

    "nextImplementationDelay()"(overrides?: CallOverrides): Promise<BigNumber>;

    nextImplementationTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    "nextImplementationTimestamp()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pausedInvesting(overrides?: CallOverrides): Promise<BigNumber>;

    "pausedInvesting()"(overrides?: CallOverrides): Promise<BigNumber>;

    profitSharingDenominator(overrides?: CallOverrides): Promise<BigNumber>;

    "profitSharingDenominator()"(overrides?: CallOverrides): Promise<BigNumber>;

    profitSharingNumerator(overrides?: CallOverrides): Promise<BigNumber>;

    "profitSharingNumerator()"(overrides?: CallOverrides): Promise<BigNumber>;

    rewardPool(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardPool()"(overrides?: CallOverrides): Promise<BigNumber>;

    rewardToken(overrides?: CallOverrides): Promise<BigNumber>;

    "rewardToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    sell(overrides?: CallOverrides): Promise<BigNumber>;

    "sell()"(overrides?: CallOverrides): Promise<BigNumber>;

    sellFloor(overrides?: CallOverrides): Promise<BigNumber>;

    "sellFloor()"(overrides?: CallOverrides): Promise<BigNumber>;

    underlying(overrides?: CallOverrides): Promise<BigNumber>;

    "underlying()"(overrides?: CallOverrides): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<BigNumber>;

    "vault()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    nextImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nextImplementation()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextImplementationDelay(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nextImplementationDelay()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextImplementationTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nextImplementationTimestamp()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pausedInvesting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "pausedInvesting()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    profitSharingDenominator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "profitSharingDenominator()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    profitSharingNumerator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "profitSharingNumerator()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rewardPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "rewardPool()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rewardToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "rewardToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sell(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "sell()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sellFloor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "sellFloor()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    underlying(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "underlying()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "vault()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
