/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MintrInterface extends ethers.utils.Interface {
  functions: {
    "mint(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "mint", values: [string]): string;

  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;

  events: {};
}

export class Mintr extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MintrInterface;

  functions: {
    mint(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

    "mint(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  mint(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

  "mint(address)"(
    arg0: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    mint(arg0: string, overrides?: CallOverrides): Promise<void>;

    "mint(address)"(arg0: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    mint(arg0: string, overrides?: Overrides): Promise<BigNumber>;

    "mint(address)"(arg0: string, overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    mint(arg0: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "mint(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
